---
services:
  frontend:
    image: ghcr.io/1alphabyte/domain-tracker:frontend
    container_name: domaintrk
    depends_on:
      - backend
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
    environment:
      - address=localhost:8080
    ports:
      - 8080:8080
    restart: unless-stopped

  backend:
    image: ghcr.io/1alphabyte/domain-tracker:backend
    volumes:
      - data:/usr/src/app
    container_name: domaintrk_backend
    restart: unless-stopped

volumes:
  data:
