name: Build and Push Docker Image
"on":
  push:
    branches:
      - main
jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Build and push Domain Tracker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "ghcr.io/1alphabyte/domain-tracker"